
import React, { useRef } from 'react';
import { GeneratedIdentity } from '@/lib/archetypes';
import { useArchetype } from '@/context/ArchetypeContext';
import { ArrowLeft, Save } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { getArchetypeDescription } from '@/lib/archetypeDescriptions';
import html2canvas from 'html2canvas';

interface IdentityResultProps {
  identity: GeneratedIdentity;
}

const IdentityResult: React.FC<IdentityResultProps> = ({ identity }) => {
  const { resetSelections, selectedFoundation, selectedExpression, selectedFunction } = useArchetype();
  const navigate = useNavigate();
  const resultRef = useRef<HTMLDivElement>(null);

  const handleRestart = () => {
    resetSelections();
    navigate('/selection');
  };

  const handleSave = async () => {
    if (!resultRef.current) {
      toast.error("Unable to generate image");
      return;
    }

    try {
      // Show loading toast
      toast.loading("Generating your archetype image...");
      
      // Create temporary element for clean export
      const exportDiv = document.createElement('div');
      exportDiv.className = "archetype-export bg-[#222222] p-8 rounded-xl text-white";
      exportDiv.style.width = "600px";
      exportDiv.style.position = "absolute";
      exportDiv.style.left = "-9999px";
      document.body.appendChild(exportDiv);
      
      // Fill with formatted content
      exportDiv.innerHTML = `
        <div class="text-center px-6 py-8 bg-[#222222] rounded-xl">
          <div class="mb-6 flex justify-center gap-4">
            ${identity.emojis.map(emoji => `<span class="text-5xl">${emoji}</span>`).join('')}
          </div>
          
          <h2 class="text-4xl font-bold mb-4 text-white">${identity.title}</h2>
          
          <div class="mb-6 text-lg leading-relaxed text-gray-300">
            ${identity.description}
          </div>
          
          <div class="grid grid-cols-2 gap-4 mb-6">
            <div>
              <h3 class="text-green-400 font-semibold mb-2">Strengths</h3>
              <ul class="text-left text-gray-300 list-disc list-inside">
                ${identity.strengths.map(s => `<li>${s}</li>`).join('')}
              </ul>
            </div>
            
            <div>
              <h3 class="text-red-400 font-semibold mb-2">Challenges</h3>
              <ul class="text-left text-gray-300 list-disc list-inside">
                ${identity.challenges.map(c => `<li>${c}</li>`).join('')}
              </ul>
            </div>
          </div>
          
          <div class="flex flex-wrap gap-2 justify-center">
            ${identity.traits.map(trait => 
              `<span class="text-xs bg-white/10 px-2 py-1 rounded">${trait}</span>`).join('')}
          </div>
          
          <div class="mt-8 text-center text-xs text-gray-500">
            Generated by Archetype - Maiba Studio
          </div>
        </div>
      `;
      
      // Generate canvas from the hidden element
      const canvas = await html2canvas(exportDiv, {
        backgroundColor: "#222222",
        scale: 2, // Better resolution
        logging: false,
        useCORS: true
      });
      
      // Convert to JPEG and download
      canvas.toBlob((blob) => {
        if (blob) {
          // Create download link
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.download = `${identity.title.replace(/\s+/g, '-').toLowerCase()}-archetype.jpg`;
          link.href = url;
          link.click();
          
          // Clean up
          URL.revokeObjectURL(url);
          document.body.removeChild(exportDiv);
          toast.dismiss();
          toast.success('Archetype image saved!');
        } else {
          toast.dismiss();
          toast.error('Failed to generate image');
        }
      }, 'image/jpeg', 0.95);
      
    } catch (error) {
      toast.dismiss();
      toast.error('Error generating image');
      console.error('Error generating image:', error);
    }
  };

  // Display emojis in their original order
  const displayEmojis = [...identity.emojis];

  return (
    <div className="w-full max-w-sm mx-auto px-4 py-4 animate-fade-in" ref={resultRef}>
      <section id="identity-core" className="text-center mb-8 w-full">
        <div id="glyphs" className="mb-6 flex justify-center gap-4">
          {displayEmojis.map((emoji, index) => (
            <span 
              key={index} 
              className="text-4xl animate-float" 
              style={{ animationDelay: `${index * 0.2}s` }}
            >
              {emoji}
            </span>
          ))}
        </div>
        
        <h2 className="text-3xl font-bold mb-3">{identity.title}</h2>
        
        <p className="text-gray-400 text-lg leading-relaxed mb-8">
          {identity.description}
        </p>
      </section>
      
      <section id="archetype-details" className="w-full space-y-4 mb-8">
        {/* Foundation */}
        <div id="foundation" className="bg-white/5 rounded-xl p-4">
          <h3 className="text-crimson font-semibold mb-2 flex items-center gap-2">
            <span>◉</span> Foundation: {selectedFoundation?.name}
          </h3>
          <p className="text-gray-300 text-sm">
            {getArchetypeDescription(selectedFoundation?.id || '')}
          </p>
        </div>

        {/* Expression */}
        <div id="expression" className="bg-white/5 rounded-xl p-4">
          <h3 className="text-crimson font-semibold mb-2 flex items-center gap-2">
            <span>◉</span> Expression: {selectedExpression?.name}
          </h3>
          <p className="text-gray-300 text-sm">
            {getArchetypeDescription(selectedExpression?.id || '')}
          </p>
        </div>

        {/* Function */}
        <div id="function" className="bg-white/5 rounded-xl p-4">
          <h3 className="text-crimson font-semibold mb-2 flex items-center gap-2">
            <span>✧</span> Function: {selectedFunction?.name}
          </h3>
          <p className="text-gray-300 text-sm">
            {getArchetypeDescription(selectedFunction?.id || '')}
          </p>
        </div>

        {/* Identity Traits */}
        <div id="identity-traits" className="bg-white/5 rounded-xl p-4 space-y-4">
          {/* Strengths */}
          <div id="strengths">
            <h3 className="text-green-400 text-sm font-semibold mb-2">Strengths</h3>
            <ul className="text-gray-300 text-sm list-disc list-inside">
              {identity.strengths.map((strength, index) => (
                <li key={index}>{strength}</li>
              ))}
            </ul>
          </div>
          
          {/* Challenges */}
          <div id="challenges">
            <h3 className="text-red-400 text-sm font-semibold mb-2">Challenges</h3>
            <ul className="text-gray-300 text-sm list-disc list-inside">
              {identity.challenges.map((challenge, index) => (
                <li key={index}>{challenge}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Key Attributes */}
        <div id="adjectives" className="bg-white/5 rounded-xl p-4">
          <h3 className="text-crimson font-semibold mb-2 flex items-center gap-2">
            <span>✧</span> Key Attributes
          </h3>
          <div className="flex flex-wrap gap-2">
            {identity.traits.map((trait, index) => (
              <span 
                key={index} 
                className="text-xs bg-white/10 px-2 py-1 rounded"
              >
                {trait}
              </span>
            ))}
          </div>
        </div>
      </section>
      
      <section id="action-buttons" className="flex gap-4 w-full">
        <button 
          onClick={handleRestart}
          className="flex-1 bg-transparent border-2 border-crimson text-crimson rounded-xl py-3 font-semibold hover:bg-crimson hover:text-white transition-colors flex items-center justify-center"
        >
          <ArrowLeft size={18} className="mr-2" /> Restart
        </button>
        <button 
          onClick={handleSave}
          className="flex-1 bg-crimson text-white rounded-xl py-3 font-semibold hover:bg-crimson/90 transition-colors flex items-center justify-center"
        >
          <Save size={18} className="mr-2" /> Save Image
        </button>
      </section>
    </div>
  );
};

export default IdentityResult;
